query($query:String!) {
  search(query:$query, type:ISSUE, first:10) {
    nodes {
      ...on Issue {
        id,
        title,
        url,
        state,
        createdAt,
        repository {
          id,
          name,
          url
        },
        labels(first:10) {
          nodes {
            id,
            name,
            color
          }
        }
      }
    }
  }
}
