query($query:String!, $pageCursor:String) {
  search(query:$query, type:ISSUE, first:15, after:$pageCursor) {
    edges {
      node {
        ...on Issue {
          id,
          title,
          url,
          state,
          createdAt,
          repository {
            id,
            name,
            url
          },
          labels(first:10) {
            nodes {
              id,
              name,
              color
            }
          }
        }
      }
    }
    pageInfo {
      endCursor,
      hasNextPage
    }
  }
}
